<div class="news">
    <?php
    /** @var NewsList $block */

    use Elogic\News\Block\NewsList;

    $newsCollection = $block->getNewsCollection();
        if ($newsCollection->getSize() > 0) :
    ?>
    <div class="toolbar top">
        <?php echo $block->getPagerHtml(); ?>
    </div>
            <ul>
                <?php foreach ($newsCollection as $news) : ?>
                    <li>
                        <div class="news-list">
                            <a class="news-title" href="<?php echo $this->getUrl('news/index/index',
                                ['news_id' => $news->getId()]) ?>"><?php echo $news->getTitle() ?></a>
                            <div class="news-list-content">
                                <?php echo $news->getSummary() ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>

            <div style="clear: both"></div>

            <div class="toolbar-bottom">
                <div class="toolbar bottom">
                    <?php echo $block->getPagerHtml(); ?>
                </div>
            </div>
        <?php else : ?>
            <p><?php echo __('Have no article!') ?></p>
        <?php endif; ?>
</div>
