<?php
/**
 * Elogic Frontend Template Widget News
 *
 * @category Elogic
 * @Package Elogic/News
 * @copyright 2021 Elogic
 */

/** @var News $block */

use Elogic\News\Block\Widget\News;

$newsCollection = $block->getNewsCollection();
$newsTitleWidget = $block->getData('title');
if ($newsCollection->getSize() > 0) :
?>
<div>
    <h3><b><?php echo $newsTitleWidget ?></b></h3>
    <ul>
        <?php foreach ($newsCollection as $news) : ?>
            <li>
                <h5><?php echo $news->getNewsTitle() ?></h5>
                <h5><a href="<?php echo $news->getLink() ?>">Link to this news</a></h5>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php else : ?>
        <p><?php echo __('Have no widget!') ?></p>
    <?php endif; ?>
</div>
